### ISSUE TITLE
Error On split command

### ISSUE THREAD

**Issue by balajimuthukrish** [samthor/kuto#1]
### Error On split command

**Steps To reproduce** 
1. npm install kuto
2. kuto split index.87aecb75.js out/ (executed split on bundle file and I am trying this on vue).
and got Following Error 
`.nvm/versions/node/v12.22.10/bin/kuto: 1: Syntax error: "(" unexpected`

I was not sure about how to install kuto and will this work on latest node versions?

**Comment by samthor** [comment]
Oh - Kuto probably needs Node 18+ to run.

I can check what features it needs later, but 12 is too old.

**Comment by samthor** [comment]
Kuto should now run on Node 14+.
