### ISSUE TITLE
kudo split failed with `babel-node: not found` error

### ISSUE THREAD

**Issue by ryota-murakami** [samthor/kuto#3]
Hi! I came from [This week React Newsletter](https://thisweekinreact.com/) and tried immediately.  
However I got this error.
Do you have any clue?

```console
~/nsx (main|✔) $ kudo split ./build/assets/vendor-CSTRa8yc.js
/Users/ryota.murakami/Library/pnpm/kudo: line 16: exec: babel-node: not found
```

## Reproduction
- 	`curl https://get.volta.sh | bash`
- `git clone git@github.com:laststance/nsx.git --depth 1`
- `cd nsx && pnpm i && pnpm build`
- `pnpm i -g kudo`
-  `kudo split ./build/assets/vendor-<random-string>.js`

## Environment
```console
~/nsx (main|✔) $ envinfo --system --Binaries

  System:
    OS: macOS 14.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 941.59 MB / 16.00 GB
    Shell: 3.7.1 - /usr/local/bin/fish
  Binaries:
    Node: 20.12.0 - ~/.volta/tools/image/node/20.12.0/bin/node
    Yarn: 1.22.22 - ~/.volta/tools/image/yarn/1.22.22/bin/yarn
    npm: 10.5.0 - ~/.volta/tools/image/node/20.12.0/bin/npm
    pnpm: 8.15.5 - ~/Library/pnpm/pnpm
    bun: 1.0.36 - ~/.bun/bin/bun
```

**Comment by samthor** [comment]
I think you've installed "kudo", not "[kuto](https://www.npmjs.com/package/kuto)".

**Comment by ryota-murakami** [comment]
@ryota-murakami Thanks! So foolishness me 😅

**Comment by samthor** [comment]
No worries! Let me know if Kuto is useful to you!
