### ISSUE TITLE
Wrapping exports in arrow functions causes `this` issues

### ISSUE THREAD

**Issue by samlaycock** [samthor/kuto#8]
Looking at the generated output, the named exports from the generated bundles are wrapped in arrow functions. This means exported code that (badly) makes assumptions about the context of `this` will not work as expected. It might be worth updating the implementation to set `globalThis` as the explicit context for the exported function calls?

**Comment by samthor** [comment]
Can you provide an example of code that wouldn't work?

**Comment by samlaycock** [comment]
Simplest way to get a repro for this is to demonstrate what the output is doing: [https://codesandbox.io/p/sandbox/nice-thunder-k2fy53](https://codesandbox.io/p/sandbox/nice-thunder-k2fy53)

I've lifted an example "bad" line from the `kuto` generated bundles from our app and imported and called it in the same way the current `kuto` corpus does.

**Comment by samlaycock** [comment]
Sorry, clarification. Actually thinking about it, it's not the arrow function wrapping, but the implicit conversion to a `module` bundle itself that causes this to break.

**Comment by samthor** [comment]
Yeah, this is an interesting problem: Kuto forces you to ship as ESM, and if your target/bundler/source used `this` at the top-level (not supported in ESM), Kuto won't work for you.

I don't think there's a "trivial" fix—it needs code rewriting.

It might be possible to fix this with Kuto, but&hellip; maybe you could also use esbuild to rebuild your code with `--format=esm` before passing to Kuto. esbuild (and probably other tools too) will generate the usual extra boilerplate to deal with your code assuming global `this`.

**Comment by samthor** [comment]
Also, I actually wonder how much code _assumes_ `this` is available as a global, because in my experience it's not that common _because_ people are hoping for better interop. For instance, `globalThis` has been around since ~2018 or so and it's nearly always the right choice.

**Comment by samlaycock** [comment]
For context, it's a bundle produced by `metro` (a `react-native-web` project) that has the top level `this` code. Hermes doesn't support ESM so it's probably likely that React Native projects are the space where this is more common. 

But to your point, I'd be surprised to see much of this beyond that.
